; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: extra libraries, dependencies
;   Advanced options: extra scripting

[env:m5stack-stamps3]
platform = espressif32@6.10.0
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
build_flags =
	-DARDUINO_USB_MODE=1
	; -D WIFI_SSID=\"your_ssid\"
	; -D WIFI_PASSWORD=\"your_password\"
	; -D VIDEO_FEED_URL=\"http://192.168.1.199/video_feed\"
lib_deps =
	m5stack/M5Unified@^0.2.1
	bodmer/TJpg_Decoder@^1.1.0
